### ISSUE TITLE
Custom node names get lost when I unplug and then plug USB dongle back

### ISSUE THREAD

**Issue by lubomirkamensky** [bigclownlabs/bch-gateway#8]
I define custom node names using Rename clause of the config file. It works fine until the USB dongle is unplugged and plugged back. Then some custom node names get lost. To get them back the bcg-ud process has to be restarted.

This scenario introduces some unwanted chaos to my sensor network order so I would be very happy to avoid that :)

**Comment by blavka** [comment]
Hi,
we removed the node names from the configuration file, but we added the option to change over mqtt, these renames are stored in the eeprom memory on the gateway.

Set node alias

mosquitto_pub -t 'gateway/{name}/alias/set' -m '{"id": "id-node", "alias": "new-name"}'

Remove node alias

mosquitto_pub -t 'gateway/{name}/alias/remove' -m '"{id-node}"'
mosquitto_pub -t 'gateway/{name}/alias/set' -m '{"id": "id-node", "alias": null}'

**Comment by lubomirkamensky** [comment]
I tested the new way, rename over MQTT, but the behavior is the same.  It works fine until the USB dongle is unplugged and plugged back. Then some custom node names get lost.  To get them back I need to rename them again.

**Comment by lubomirkamensky** [comment]
should I create a new issue or this one can be reopened?

**Comment by hubpav** [comment]
Hi, I have reopened the issue. Thx.

**Comment by blavka** [comment]
Hi,
bug had in firmware, try update on
bigclownlabs/bcf-gateway-core-module:v1.9.0                  
bigclownlabs/bcf-gateway-usb-dongle:v1.9.0
